// Fails when UI copy, docs or code contain an em dash or a gradient.
// Brand rules: no em dashes anywhere, no gradient colours.
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

const IGNORED = [
  /^package-lock\.json$/,
  /^AGENTS\.md$/, // generated by Next.js, rewritten by `next dev`
  /^types\/database\.ts$/,
  /^scripts\/check-style\.mjs$/,
  /\.(png|jpe?g|webp|ico|gif|woff2?)$/,
]

const RULES = [
  { name: 'em dash', pattern: /—/ },
  {
    name: 'gradient',
    pattern:
      /(linear|radial|conic)-gradient\(|\bbg-(gradient|linear|radial|conic)-|\b(from|via|to)-\[?#/,
  },
]

const files = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard'], {
  encoding: 'utf8',
})
  .split('\n')
  .filter(Boolean)
  .filter((file) => !IGNORED.some((re) => re.test(file)))

const problems = []
for (const file of files) {
  let text
  try {
    text = readFileSync(file, 'utf8')
  } catch {
    continue
  }
  text.split('\n').forEach((line, index) => {
    for (const rule of RULES) {
      if (rule.pattern.test(line))
        problems.push(`${file}:${index + 1} ${rule.name}: ${line.trim()}`)
    }
  })
}

if (problems.length > 0) {
  console.error(`Style check failed (${problems.length}):\n${problems.join('\n')}`)
  process.exit(1)
}
console.log(`Style check passed (${files.length} files).`)
